### ISSUE TITLE
Encountering an issue where the code does not seem to be running

### ISSUE THREAD

**Issue by mincheulkim** [sisl/SceneInformer#1]
Hello, I would like to thank you for your excellent work. However, I encountered the following problem when I ran your code:

Global seed set to 23
Traceback (most recent call last):
  File "/SceneInformer/scripts/train_lightning.py", line 247, in <module>
    trainer_kwargs["callbacks"] = [instantiate_from_config(callbacks_cfg[k]) for k in callbacks_cfg]
  File "SceneInformer/scripts/train_lightning.py", line 247, in <listcomp>
    trainer_kwargs["callbacks"] = [instantiate_from_config(callbacks_cfg[k]) for k in callbacks_cfg]
  File "/SceneInformer/sceneinformer/utils/utils.py", line 22, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/SceneInformer/sceneinformer/utils/utils.py", line 30, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/anaconda3/envs/sceneinformer/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'

How can this issue be resolved?

Thanks,

**Comment by BenQLange** [comment]
Hi! Thanks! There was a typo in the callback config (https://github.com/sisl/SceneInformer/blob/032c959eee4b6cf9fbd3f05883513c5f9200c06d/scripts/train_lightning.py#L217). It's been addressed now. Thanks for catching it!

We will be updating this repo with occlusion dataset processing scripts (it's quite complex, hence the delay).

**Comment by BenQLange** [comment]
The repo was updated!

**Comment by Linqingh** [comment]
> Hello, I would like to thank you for your excellent work. However, I encountered the following problem when I ran your code:
> 
> Global seed set to 23 Traceback (most recent call last): File "/SceneInformer/scripts/train_lightning.py", line 247, in trainer_kwargs["callbacks"] = [instantiate_from_config(callbacks_cfg[k]) for k in callbacks_cfg] File "SceneInformer/scripts/train_lightning.py", line 247, in trainer_kwargs["callbacks"] = [instantiate_from_config(callbacks_cfg[k]) for k in callbacks_cfg] File "/SceneInformer/sceneinformer/utils/utils.py", line 22, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict())) File "/SceneInformer/sceneinformer/utils/utils.py", line 30, in get_obj_from_str return getattr(importlib.import_module(module, package=None), cls) File "/home/anaconda3/envs/sceneinformer/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 992, in _find_and_load_unlocked File "", line 241, in _call_with_frames_removed File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 992, in _find_and_load_unlocked File "", line 241, in _call_with_frames_removed File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1004, in _find_and_load_unlocked ModuleNotFoundError: No module named 'src'
> 
> How can this issue be resolved?
> 
> Thanks,

Hi. Can you please tell me which version of the dataset you are using, and which version of waymo-open-dataset-tf?
